definitions:
  api.ApiResponseCertificate:
    properties:
      certificate:
        type: string
    type: object
  api.ApiResponseError:
    properties:
      error:
        type: string
    type: object
  api.ApiResponseHost:
    properties:
      providers:
        items:
          $ref: '#/definitions/api.Provider'
        type: array
      publickey:
        type: string
    type: object
  api.ApiResponseIndex:
    properties:
      version:
        type: string
    type: object
  api.FormHostCertificate:
    properties:
      pubkey:
        type: string
      token:
        type: string
    required:
    - pubkey
    - token
    type: object
  api.Provider:
    properties:
      scopes:
        items:
          type: string
        type: array
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Return the running API version.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ApiResponseIndex'
      summary: Get API version
  /{host}:
    get:
      description: Return the CA public key and supported OpenID Connect providers
        with their required scopes.
      parameters:
      - description: Host
        example: '"example.com"'
        in: path
        name: host
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ApiResponseHost'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ApiResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiResponseError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/api.ApiResponseError'
      summary: Get host information
  /{host}/certificate:
    post:
      consumes:
      - application/json
      description: Generate and return a new SSH certificate using the given public
        key and access token.
      parameters:
      - description: Host
        example: '"example.com"'
        in: path
        name: host
        required: true
        type: string
      - description: Public key and access token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.FormHostCertificate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.ApiResponseCertificate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ApiResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ApiResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiResponseError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/api.ApiResponseError'
      summary: Generate SSH certificate
swagger: "2.0"
