version: '3.3'
services:
  oinit-ca:
    image: ghcr.io/lbrocke/oinit-ca:latest
    container_name: oinit-ca
    restart: unless-stopped
    ports:
    - 127.0.0.1:8080:80
    volumes:
    - /etc/oinit-ca/:/etc/oinit-ca/
