# This workflow will create a new Github release whenever a tag following
# semantic versioning is pushed to the main branch.

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

name: Create Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
      
      - name: Login to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          REGISTRY: "ghcr.io"
          IMAGE: "lbrocke/oinit-ca"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
