# This workflow will create a new Github release whenever a tag following
# semantic versioning is pushed to the main branch.

on:
  push:
    tags:
      - v*.*.*

name: Create Release

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      # Make sure tag was pushed to main branch
      - name: Check branch
        if: endsWith(env.BRANCH, 'main') == false
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
      
      - name: Login to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          REGISTRY: "ghcr.io"
          IMAGE: "belfhi/oinit-ca"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
